/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok2.app;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class Overview extends javax.swing.JFrame {

    /**
     * Creates new form Overview
     */
    public Overview() {
        initComponents(); 
        chart.setTitle("UMP");
        chart.addLegend("amount", Color.red, Color.green);
        chart1.setTitle("Bahan Pangan");
        chart1.addLegend("amount", Color.green, Color.blue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curveLineChart1 = new com.kelompok2.chart.CurveLineChart();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        panelGradient1 = new com.kelompok2.panel.PanelGradient();
        panelGradient2 = new com.kelompok2.panel.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        panelGradient3 = new com.kelompok2.panel.PanelGradient();
        chart1 = new com.kelompok2.chart.CurveLineChart();
        chart = new com.kelompok2.chart.CurveLineChart();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));

        panelGradient1.setBackground(new java.awt.Color(24, 43, 61));
        panelGradient1.setColorGradient(new java.awt.Color(19, 51, 89));

        panelGradient2.setBackground(new java.awt.Color(19, 51, 89));
        panelGradient2.setForeground(new java.awt.Color(24, 43, 61));
        panelGradient2.setColorGradient(new java.awt.Color(24, 43, 61));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Overview");
        panelGradient2.add(jLabel1);
        jLabel1.setBounds(10, 20, 130, 40);

        panelGradient3.setBackground(new java.awt.Color(19, 51, 89));
        panelGradient3.setColorGradient(new java.awt.Color(24, 43, 61));
        panelGradient3.add(chart1);
        chart1.setBounds(250, 10, 200, 210);
        panelGradient3.add(chart);
        chart.setBounds(30, 10, 200, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGradient2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(panelGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Overview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kelompok2.chart.CurveLineChart chart;
    private com.kelompok2.chart.CurveLineChart chart1;
    private com.kelompok2.chart.CurveLineChart curveLineChart1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private com.kelompok2.panel.PanelGradient panelGradient1;
    private com.kelompok2.panel.PanelGradient panelGradient2;
    private com.kelompok2.panel.PanelGradient panelGradient3;
    // End of variables declaration//GEN-END:variables
}
